# Documentacoes
# docker scout cves: https://docs.docker.com/reference/cli/docker/scout/cves/
# Integracao com Azure DevOps
trigger:
- main

variables:
  vmImageName: 'ubuntu-latest'
  projectDirectory: './src/WorkerContagem/'

stages:
- stage: ImageScanning
  displayName: Image Scanning stage
  variables:
  - group: docker-scout
  jobs:
  - job: ImageScanning
    displayName: ImageScanning
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: |
        docker pull docker/scout-cli:latest
      displayName: Baixar imagem do Docker Scout CLI
    - script: |
        cd $(projectDirectory)
        docker build . -t image-to-scan-test:$(Build.BuildNumber) --no-cache
      displayName: Build da imagem para analise
    - script: |
        docker images
      displayName: Exibir imagens no ambiente
    - script: |
        cd $(projectDirectory)
        echo '**** Diretorio:'
        echo $PWD
        echo ''
        chmod -R 777 .
        echo 'Permissoes apos ajustes'
        ls -ld
      displayName: Configurar permissoes de diretorio para uso do Docker Scout
    - script: |
        echo 'Usuario no Docker Hub: $(DOCKER_HUB_USER)'
        echo $(DOCKER_HUB_PAT) | docker login -u $(DOCKER_HUB_USER) --password-stdin
      displayName: Login no Docker Hub com Personal Access Token
    - script: |
        docker run --rm docker/scout-cli:latest
      displayName: Exibir opções da linha de comando do Docker Scout
    - script: |
        docker run -t \
          -e DOCKER_SCOUT_HUB_USER=$(DOCKER_HUB_USER) \
          -e DOCKER_SCOUT_HUB_PASSWORD=$(DOCKER_HUB_PAT) \
          -u root -v /var/run/docker.sock:/var/run/docker.sock \
          docker/scout-cli:latest \
          cves image-to-scan-test:$(Build.BuildNumber) --exit-code --only-severity critical,high
      displayName: Executar Docker Scout analisando vulnerabilidades e exibindo resultados em tela
    - script: |
        docker run -t \
          -e DOCKER_SCOUT_HUB_USER=$(DOCKER_HUB_USER) \
          -e DOCKER_SCOUT_HUB_PASSWORD=$(DOCKER_HUB_PAT) \
          -v $(Build.SourcesDirectory):/mnt \
          -u root -v /var/run/docker.sock:/var/run/docker.sock \
          docker/scout-cli:latest \
          cves --format markdown --output /mnt/scan-image.md image-to-scan-test:$(Build.BuildNumber) --exit-code --only-severity critical,high
      displayName: Executar Docker Scout analisando vulnerabilidades (geracao arquivo Markdown)
      condition: always()
    - script: |
        ls
      displayName: Exibir arquivos no diretorio-raiz apos execucao do Docker Scout
      condition: always()
    - task: PublishMarkdownReports@1
      inputs:
        contentPath: '$(Build.SourcesDirectory)'
        indexFile: 'scan-image.md'
      displayName: Publicacao de relatorio Markdown
      condition: always()